---
- name: Stop Apigee Service
  command: 'removes=/opt/apigee/apigee-service /opt/apigee/apigee-service/bin/apigee-all stop'
  
- name: Uninstall Apigee Service
  command: 'removes=/opt/apigee/apigee-service /opt/apigee/apigee-service/bin/apigee-service apigee-service uninstall'
  
- name: Clear the yum cache
  shell: sudo yum clean all
  
- name: Remove Apigee RPMs
  package:
    name: apigee*
    state: absent

- name: Remove edge RPMs
  package:
    name: edge*
    state: absent

- name: Remove the installation root directory
  become: yes
  file:
    path: /opt/apigee
    state: absent

- name: Remove the Nginx directory
  become: yes
  file:
    path: /opt/nginx
    state: absent

- name: Unconditionally reboot the machine with all defaults
  become: yes
  reboot: